version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/PES-FE
    overwrite: yes
file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ubuntu/PES-FE
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  ApplicationStop: []
  AfterInstall:
    - location: deploy.sh
      timeout: 300
      runas: ubuntu
    - location: cleanup.sh
      timeout: 300
      runas: ubuntu