name: Continuous Deployment # Workflow 이름

on: # Event 감지
  push: # 해당 브랜치의 푸쉬가 일어날 때 CI/CD를 진행하겠다는 뜻
    branches: [ "main" ]
jobs:
  develop-deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: zip create
        # zip 파일을 만듭니다(파일명은 자유, 대신 아래 workflow에 적을 파일명과 동일하게 맞춰주세요).
        # 여기서는 build-app.zip
        run: zip -qq -r ./build-app.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3 # Upload build file to S3
        run: aws s3 cp ./build-app.zip s3://pes-front-deploy/build-app.zip --region ${{ secrets.AWS_REGION }}

      - name: Deploy # Deploy to EC2
        run: |
          aws deploy create-deployment \
            --application-name code-deploy-front \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name code-deploy-group \
            --s3-location bucket=pes-front-deploy,key=build-app.zip,bundleType=zip
